### ISSUE TITLE
Notification button and config button have the same key.

### ISSUE THREAD

**Issue by jberwick-splunk** [splunk/timelapse-vis#11]
> react_devtools_backend.js:3973 Warning: Each child in a list should have a unique "key" prop.
VM2242 react_devtools_backend.js:3973 Warning: Encountered two children with the same key, `left`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in td (created by SplunkTimeRangeSliderInput)
    in tr (created by SplunkTimeRangeSliderInput)
    in tbody (created by SplunkTimeRangeSliderInput)
    in table (created by SplunkTimeRangeSliderInput)
    in Fe (created by SplunkThemeProvider)
    in SplunkThemeProvider (created by SplunkTimeRangeSliderInput)
    in div (created by SplunkTimeRangeSliderInput)
    in SplunkTimeRangeSliderInput (at rangeslider/index.jsx:17)
    in div (at rangeslider/index.jsx:16)
    in LayerStackGlobalProvider

**Comment by ryanwoconnor** [comment]
Fixed in #12
